### ISSUE TITLE
Creature - Westfall : Westfall Brigade Guard

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#10]
Quest/Spell/Item/Creature(ID) The ID is: 51915

The Current Behaviour is as following: These 2 guards in the screenshot are level 85 and are oneshotting the riverpaws before the player can attack them. Coordinates (51,53).

Expected Behaviour should be as following: These 2 guards should be level 23 like the other Sentinel Hill guards or level 40 like the other Westfall Brigade Guards.

Screenshot/Video (IMGUR/YOUTUBE): 
![image](https://user-images.githubusercontent.com/65196200/98796152-5db03000-240b-11eb-8035-9f50e564f934.png)

Additional Information:

**Comment by omghixd** [comment]
This issue is now resolved and i have also cleaned up the battlefield within Sentinel Hill. Should be in a much better shape now 👍 

//Fixed and Closing this report.
