### ISSUE TITLE
Quest - Northern Barrens : Ignition

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#101]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[858](https://cata-twinhead.twinstar.cz/?quest=858)_**

The Current Behaviour is as following: 

Expected Behaviour should be as following: 
**_This [quest item](https://cata-twinhead.twinstar.cz/?item=5050) should have a 100% drop chance_**
**_[Npc](https://cata-twinhead.twinstar.cz/?npc=3445) has a double spawn aswell, as do all the other creatures in and around this platform_**

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by UtilExe** [comment]
Will be fixed with a major quest item drop correction
