### ISSUE TITLE
Quest - Northern Barrens : Competition Schmompetition

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#102]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[29086](https://cata-twinhead.twinstar.cz/?quest=29086)_**

The Current Behaviour is as following: 

Expected Behaviour should be as following: 
**_This [quest item](https://cata-twinhead.twinstar.cz/?item=68820l) should have to following drop rates:
https://cata-twinhead.twinstar.cz/?item=68820_**

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by UtilExe** [comment]
Will be fixed with a major quest item drop correction
