### ISSUE TITLE
Quest - Searing Gorge : Rasha'krak

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#107]
Quest/Spell/Item/Creature(ID) The ID is: 28099
Spell/Creature/Object-ID (Specify Accordingly): creature=47553

The Current Behaviour is as following: When I killed Rasha'krak he did not drop Rasha'krak's Bracers of Binding.

Expected Behaviour should be as following: He should drop his quest item with 100% chance.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Quest item "Rasha'Krak's Bracers of Binding" was given 100% Drop Chance instead of 56%.

I seriously do not understand why Blizzard keep half'ing Drop Percentages on items that only drop from one mobe.

//Fixes and Closes this Report.
