### ISSUE TITLE
Creatures - Duskbat Model Size and Speed

### ISSUE THREAD

**Issue by PlaguedScarecrow** [omghixd/Path-of-Classic-Bugtracker#11]
Creature ID is:  1512 (Duskbat)

The Current Behavior is as following: The model size is small and the creature moves to fast.

Expected Behavior should be as following: The model size should be bigger and the creature should move slower.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
The creature now has been given its correct size and correct speed. 

Thank you for this report!
//Fixed and Closing this report.
