### ISSUE TITLE
Instances - Zul'Farrak : Shallow Grave

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#111]
Quest/Spell/Item/Creature(ID) The ID is: 128308

The Current Behaviour is as following: Some of the graves can spawn infinite Zul'Farrak Dead Hero and Zul'farrak Zombie. It still only spawns a few on each click but there is no cap on how many times you can click it and spawn zombies.

Expected Behaviour should be as following: You should not be able to click the graves an infinite number of times.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
This should no longer happen, you are now able to enter the dungeon and loot the grave. If the grave is looted entirely it will despawn as it should. If the loot is not taken the grave will stay until said loot is collected. this will also no longer spawn infinite amount of Zombies.

//Fixes and Closes this Report.
