### ISSUE TITLE
Creature - Lower Blackrock Spire : Gizrul the Slavener

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#113]
Quest/Spell/Item/Creature(ID) The ID is: 10268

The Current Behaviour is as following: There are 2 Gizrul the Slavener in Lower Blackrock Spire. One runs down the stairs after you kill Halycon as expected, the other one stands at the top of the stairs.

Expected Behaviour should be as following: There should only be one Gizrul the Slavener, the one that runs down the stairs.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Removed the dupe.

//Fixes and Closes this Report.
