### ISSUE TITLE
Flametongue weapon deals extreme damage.

### ISSUE THREAD

**Issue by FiurWoW** [omghixd/Path-of-Classic-Bugtracker#117]
Quest/Spell/Item/Creature(ID) The ID is: 
Spell ID: 8024

The Current Behaviour is as following: 
It deals extreme amount of damage.
I am level 11 and does between 150-260 damager PER HIT.

Expected Behaviour should be as following: 
Not so much damage, I do not know the correct scaling.

Screenshot/Video (IMGUR/YOUTUBE): 
https://cdn.discordapp.com/attachments/619154914710650915/782012702867324969/unknown.png

Additional Information:
Spell link: https://cata-twinhead.twinstar.cz/?spell=8024

**Comment by UtilExe** [comment]
Test on next server update please (probably tomorrow by now)
