### ISSUE TITLE
Blasted Lands : Mining Node

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#118]
Quest/Spell/Item/Creature(ID) The ID is: 

The Current Behaviour is as following: There is both a mithril, iron and gold deposit within the node on the screenshot. And it is up in the air.

Expected Behaviour should be as following: These nodes should not be in the air.

Screenshot/Video (IMGUR/YOUTUBE): 
![WoWScrnShot_110320_205410](https://user-images.githubusercontent.com/65196200/98034123-c77e7780-1e16-11eb-8fd5-8c854c1a5ed2.jpg)

Additional Information: Coordinates (60,37)

**Comment by WernerBureau** [comment]
This has been fixed, and the rest of the zone has been checked for mining / herb nodes.
