### ISSUE TITLE
Lack of Razormane Pillager at Grol'dom Farm

### ISSUE THREAD

**Issue by Sundorian** [omghixd/Path-of-Classic-Bugtracker#120]
Quest/Spell/Item/Creature(ID) The ID is: 34503

The Current Behaviour is as following: major lack of this creature at Grol'dom Farm

Expected Behaviour should be as following: Should be a whole lot more

Screenshot/Video (IMGUR/YOUTUBE): 
![WoWScrnShot_110320_154328](https://user-images.githubusercontent.com/45952468/98044154-1236ca00-1dec-11eb-922a-bb1a6517e3a6.jpg)

Additional Information:

**Comment by omghixd** [comment]
Added a few more creatures where the blue area on the minimap/map suggest where there should be quest-objective related creatures. 

//Fixes and Closes this Report.
