### ISSUE TITLE
Quests - Small Colored Pouch Drop Rates

### ISSUE THREAD

**Issue by PlaguedScarecrow** [omghixd/Path-of-Classic-Bugtracker#122]
Item ID is:  805 (Small Red Pouch), 5572 (Small Green Pouch), 4496 (Small Brown Pouch), 5571 (Small Black Pouch), 828 (Small Blue Pouch)

Creature ID is: 49422 (Rotbrain Berserker), 49423 (Rotbrain Magus)

The Current Behavior is as following:  High drop rate on Small Colored Pouches. Seems to be roughly 10% per pouch.

Expected Behavior should be as following:  Lower drop rate on Small Colored Pouches. Should be 0.1% - 0.2%

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Did notice the high amount of drop rate for these. They were ranging from 20% to all the way up to 58%. These were all brought down to 0.1% and 0.2% as Classic Wowhead suggests.

//Fixes and Closes this Report.
