### ISSUE TITLE
Items - Quest Item Dropping from Extra Mobs

### ISSUE THREAD

**Issue by PlaguedScarecrow** [omghixd/Path-of-Classic-Bugtracker#123]
Item The ID is: 3264 (Duskbat Wing), 3265 (Scavenger Paw)

Creature ID is: 49422 (Rotbrain Berserker), 49423 (Rotbrain Magus)

The Current Behavior is as following: Duskbat Wing and Scavenger Paw are quest items dropping from Rotbrain Berserker and Rotbrain Magnus.

Expected Behavior should be as following: These quest items should not drop from these creatures.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information: These quest items dropping are from an earlier quest id-26802 (The Damned) that required you to kill id-1512 (Duskbat) and id-1508 (Young Scavenger) and that quest is working as intended.

**Comment by omghixd** [comment]
There were some mobs that had these items being drop-able at a **very low** percentage. These will no longer drop them.

Instead only Duskbat(s) will drop Duskbat Wing(s) and Scavanger(s) will drop Scavanger Paw(s).

//Fixes and Closes this report.
