### ISSUE TITLE
Mage: Incanter's Flow (Gamebreaking)

### ISSUE THREAD

**Issue by omghixd** [omghixd/Path-of-Classic-Bugtracker#13]
Quest/Spell/Item/Creature(ID) The ID is: Missing Spell ID

Current behavior The Current Behaviour is as following: Incanter's Flow ramps up infinitely. I ended up doing several million damage with my Ice Lance.

Expected behavior Expected Behaviour should be as following: Incanter's Flow should build up to 20% increase damage and then diminish down to 4% increased damage, cycling every 10 sec.

Screenshots Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Currently looking into this. To be continued!

**Comment by En1gm4** [comment]
In **SpellAuraEffects.cpp**, in **AuraEffect::HandleModDamagePercentDone()**, which handles the application of auras that modify the % damage done,  during _Incanter's Flow_, the core at the moment doesn't take away the % given. We printed the sequence to the output and received the following output:

**out:** `4, -4, 4, 4, 12, -12, 4, 4, 20, -20`

meaning for 2 and for 4 stacks of _Incanter's Flow_ the core doesn't take away the increase in damage.

**Comment by En1gm4** [comment]
Problem was when changing the number of stacks, in **AuraEffect::ChangeAmount()**, the function wouldn't take away the old amount of aura effect modifier before adding the new amount, it would instead just add both the old and new amounts resulting in scaling that wouldn't be removed with the aura. This should fix the issue for other similar auras
