### ISSUE TITLE
Quest - Westfall : In Defense of Westfall

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#13]
Quest/Spell/Item/Creature(ID) The ID is: 26286
Quest/Spell/Item/Creature(ID) item=58111

The Current Behaviour is as following: Gnoll Attack Orders either have an incredibly low drop chance or does not drop at all. Killed about 40 Riverpaw Bandits/Brutes/Herbalists before moving on.

Expected Behaviour should be as following: Gnoll Attack Orders should have a higher drop chance.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by UtilExe** [comment]
Fixed
