### ISSUE TITLE
Teldrassil Chest gives no loot- cords 66.5, 44.5

### ISSUE THREAD

**Issue by dreadnought101** [omghixd/Path-of-Classic-Bugtracker#135]
![No Loot Chest 66 5 44 5](https://user-images.githubusercontent.com/10070048/100495908-1e712700-310d-11eb-908a-476c119586b5.PNG)

**Comment by philipnks** [comment]
Auto-loot causes chests to drop nothing, quite common as well.

**Comment by dreadnought101** [comment]
hum, usually i hold shift+click to individual loot chests....though I don't recall if I auto-looted this one tbh

**Comment by omghixd** [comment]
For some reason the items with the highest drop chance had a Quest Loot only mode added to it. This was reverted to becoming Normal Loot and not Quest Specific Loot. i also took the time to cleanup the area around and remove the gnell/gnolls Brutal/Cata Weapons they had int heir hand in the starting area

Thank you for reporting this
//Fixed and closing this report.
