### ISSUE TITLE
Spell: Priest Smite

### ISSUE THREAD

**Issue by Karmiven** [omghixd/Path-of-Classic-Bugtracker#137]
Quest/Spell/Item/Creature(ID) The ID is:  Spell ID 585 (smite 1 rank)

The Current Behaviour is as following: Smite use more mana, than it show. At 4 lvl, smite request by decription about 14 mana, but it use 21 mana

Expected Behaviour should be as following: just... cast spell?

Screenshot/Video (IMGUR/YOUTUBE):  https://imgur.com/a/lqKGvXm

Additional Information:

**Comment by UtilExe** [comment]
Test on next server update please (probably tomorrow by now)

**Comment by Karmiven** [comment]
Now smite use less mana than it show in description.
25 lvl, in description it show about 75 mana. but when i spell smite, it use 68 mana
