### ISSUE TITLE
Dual Specc - Can't swap

### ISSUE THREAD

**Issue by djawl** [omghixd/Path-of-Classic-Bugtracker#14]
The Current Behaviour is as following: You can buy dual specc but when you click activate nothing happens.

Expected Behaviour should be as following: When you click activate on your dual specc-specc you should do a cast and it'll swap.

Screenshot/Video (IMGUR/YOUTUBE): https://i.gyazo.com/689354816721670282bbfa6abb5ff98f.mp4

**Comment by omghixd** [comment]
Unable to reproduce

//Closed
