### ISSUE TITLE
[Teldrassil][NPC]Nightsaber Stalker can be herb gathered

### ISSUE THREAD

**Issue by jeffisdrunk** [omghixd/Path-of-Classic-Bugtracker#141]
Quest/Spell/Item/Creature(ID) The ID is: 
http://cata.cavernoftime.com/npc=2043#drop

The Current Behaviour is as following: 
You kill it. Instead of being Skinnable you can use Herb Gathering from it's corpse.

Expected Behaviour should be as following: 
Change from using [Herbalism] to [Skinning]

Screenshot/Video (IMGUR/YOUTUBE): 
https://imgur.com/a/25dpUxs

Additional Information:

**Comment by jeffisdrunk** [comment]
http://cata.cavernoftime.com/npc=2042

These Nightsabers as well

**Comment by omghixd** [comment]
These tigers no longer drop Khadgar's Whiskers upon skinning. Instead they will drop their normal Light Leather at a 100% Drop Chance.

Thank you for reporting this
//Fixed and closing this report.
