### ISSUE TITLE
Quest/Item - The Cape of Stranglethorn - Stranglethorn Fever/Gorilla Fang

### ISSUE THREAD

**Issue by En1gm4** [omghixd/Path-of-Classic-Bugtracker#145]
Intended behaviour: You kill gorillas until they drop the Gorilla Fang (id:2799), which you turn in to spawn the boss which drops the Heart of Mokk

Current Behaviour: Doesn't seem like the gorillas drop the fang

Got 73xFractured Gorilla Tooth, 20xChipped Gorilla Tooth, 1xLarge Fang, and greens, but not a single Gorilla Fang, either the actual drop rate too low, or it doesn't drop at all.

**Comment by UtilExe** [comment]
Please check now
