### ISSUE TITLE
[NPC] Gorefangs dubplicate spawn

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#148]
Quest/Spell/Item/Creature(ID) The ID is: 12431

The Current Behaviour is as following: Duplicated Gorefangs

Expected Behaviour should be as following: Only 1 Rare spawn

Screenshot/Video (IMGUR/YOUTUBE): 
https://classic.wowhead.com/npc=12431/gorefang

Additional Information:

**Comment by omghixd** [comment]
Removed the dupe and the remaining one was given a proper path and walks around the area.

Thank you for reporting this
//Fixed and closing this report.
