### ISSUE TITLE
Quest - Redridge Mountains : Yowler Must Die!

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#15]
Quest/Spell/Item/Creature(ID) The ID is: 26545
Quest/Spell/Item/Creature(ID) item=58937

The Current Behaviour is as following: Blackrock Invasion Plans does not have a 100% drop chance from Yowler.

Expected Behaviour should be as following: Blackrock Invasion Plans should have a 100% drop chance from Yowler.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by UtilExe** [comment]
Fixed
