### ISSUE TITLE
Item: Cooper Vein

### ISSUE THREAD

**Issue by Karmiven** [omghixd/Path-of-Classic-Bugtracker#150]
Quest/Spell/Item/Creature(ID) The ID is: 

The Current Behaviour is as following: Some Cooper vein in air

Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 
![image](https://user-images.githubusercontent.com/63984420/100524940-41f7a880-31c5-11eb-9826-810a30adb530.png)
![image](https://user-images.githubusercontent.com/63984420/100524946-491eb680-31c5-11eb-8dd9-0a5152119a71.png)

Additional Information:

**Comment by omghixd** [comment]
This Ore Node has been deleted and replaced with one in the ground. Change takes affect at our 04:00 GMT+1 Maintenance tonight.

Thank you for reporting this
//Fixed and closing this report.
