### ISSUE TITLE
[Quest] A Fighting Chance

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#151]
Quest/Spell/Item/Creature(ID) The ID is: 28495

The Current Behaviour is as following: Auto-Completes

Expected Behaviour should be as following: Save Hill Fawn Quest Credit with Duskingdawn's Wand

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
**I've got no idea if the Quest functions or not**
Quest: https://www.wowhead.com/quest=28495/a-fighting-chance
Quest item: https://www.wowhead.com/item=64416/duskingdawns-wand
NPC's: https://www.wowhead.com/npc=48684/hill-fawn-quest-credit

**Comment by UtilExe** [comment]
Fixed
