### ISSUE TITLE
[Quest] The Heart of the Matter

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#153]
Quest/Spell/Item/Creature(ID) The ID is: 28484

The Current Behaviour is as following: Auto-Completion

Expected Behaviour should be as following:  Kill Cave Yeti/Ferocious Yeti and receive Beating Yeti Heart.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/quest=28484/the-heart-of-the-matter

**Comment by omghixd** [comment]
This is now fixed!

//Fixed and closing this report.
