### ISSUE TITLE
[Quest] Yetimus the Yeti Lord

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#154]
Quest/Spell/Item/Creature(ID) The ID is: 28485

The Current Behaviour is as following: Auto-Completion

Expected Behaviour should be as following: Kill Yetimus The Yeti Lordand loot Yetimus' Twisted Horn

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
Quest: https://www.wowhead.com/quest=28485/yetimus-the-yeti-lord
NPC: https://www.wowhead.com/npc=47484/yetimus-the-yeti-lord

**Comment by omghixd** [comment]
This is fixed now.

//Fixed and closing this report.
