### ISSUE TITLE
[Quest] Matters of Loyalty

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#156]
Quest/Spell/Item/Creature(ID) The ID is: 28600

The Current Behaviour is as following: Nothing

Expected Behaviour should be as following: Cutscene - See youtube link

Screenshot/Video (IMGUR/YOUTUBE): 
https://www.youtube.com/watch?v=qn645jzB4XA
Additional Information:
https://www.wowhead.com/quest=28600/matters-of-loyalty

**Comment by UtilExe** [comment]
Fixed
