### ISSUE TITLE
Objects remains from vanilla in cataclysm

### ISSUE THREAD

**Issue by FiurWoW** [omghixd/Path-of-Classic-Bugtracker#158]
Quest/Spell/Item/Creature(ID) The ID is: 
Floating debris - Object ID: 180655
Barrel of milk - Object ID: 3705

The Current Behaviour is as following: 
Remains from vanilla are still shown where the water used to be in Thelsamar.
There 

Expected Behaviour should be as following: 
It should not be there at all.
This is a recurring problem and needs to be check at.

Screenshot/Video (IMGUR/YOUTUBE): 
Floating debris: https://media.discordapp.net/attachments/619154914710650915/782270452319649802/unknown.png
Floating milk: https://media.discordapp.net/attachments/619154914710650915/782270969191858176/unknown.png

Additional Information:
Floating debris link: https://cata-twinhead.twinstar.cz/?object=180655
Barrel of milk link: https://cata-twinhead.twinstar.cz/?object=3705

**Comment by omghixd** [comment]
Loch Modan has yet not been cleared for dupes and or floating objects / creatures.

It still being scheduled to be cleaned.

Thank you for reporting this.
//Fixed and closing this report.
