### ISSUE TITLE
Leftover objects in Ironforge

### ISSUE THREAD

**Issue by FiurWoW** [omghixd/Path-of-Classic-Bugtracker#159]
Quest/Spell/Item/Creature(ID) The ID is: 

The Current Behaviour is as following: 
A leftover object is shown in Ironforge (see screenshot)

Expected Behaviour should be as following: 
It should not be there or visible.

Screenshot/Video (IMGUR/YOUTUBE): 
https://media.discordapp.net/attachments/619154914710650915/782319895302897664/unknown.png

Additional Information:

**Comment by omghixd** [comment]
These should be gone by the 04:00 GMT+1 Maintenance.

Thank you for this report.
//Fixed and closing this report.
