### ISSUE TITLE
Creature - Redridge Mountains : Chatter

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#16]
Quest/Spell/Item/Creature(ID) The ID is: 616

The Current Behaviour is as following: There are several dupes of this rare. Found 6 of this NPC spread out around Alther's Mill and that part of the zone. There are possibly more.

Expected Behaviour should be as following: There should only be 1 of this rare.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Cleared the area for dupes and incorrect creature spawns and gave Chatter a sole spawn and a proper path to walk.

Thank you for reporting this!
//Fixed and Closing this report.
