### ISSUE TITLE
Gobbler's Head does not have 100% droprate while you have the quest.

### ISSUE THREAD

**Issue by FiurWoW** [omghixd/Path-of-Classic-Bugtracker#160]
Quest/Spell/Item/Creature(ID) The ID is: 
Item ID: 3618
NPC ID: 1259
Quest ID: 25801

The Current Behaviour is as following: 
The head does not have 100% droprate

Expected Behaviour should be as following: 
Head should have 100% droprate if you have the quest.

Screenshot/Video (IMGUR/YOUTUBE): 
https://media.discordapp.net/attachments/619154914710650915/782334178846572554/unknown.png

Additional Information:
Head item link: https://cata-twinhead.twinstar.cz/?item=3618
Gobbler NPC link: https://cata-twinhead.twinstar.cz/?npc=1259
Quest link: https://cata-twinhead.twinstar.cz/?quest=25801

**Comment by omghixd** [comment]
The item will now have a 100% drop rate if you have the quest.

Thank you for this report!

//Fixed and closing this report.
