### ISSUE TITLE
Vendor sells cataclysm recipes

### ISSUE THREAD

**Issue by dreadnought101** [omghixd/Path-of-Classic-Bugtracker#161]
NPC in Stormwind-- Kaita Deepforge

![Cata Recipes](https://user-images.githubusercontent.com/10070048/100526830-dc39fb00-3189-11eb-924f-3c79af9f691d.PNG)

**Comment by omghixd** [comment]
Removed the Cataclysm Recipes from the vendor list.

Thank you for the report!

//Fixed and closing this report.
