### ISSUE TITLE
Cata / Level 85 mob in stormwind

### ISSUE THREAD

**Issue by Lucifronx** [omghixd/Path-of-Classic-Bugtracker#164]
Quest/Spell/Item/Creature(ID) The ID is: 44814

The Current Behaviour is as following: Crazed Cultists are spawned in Storm

Expected Behaviour should be as following: They should likely be removed

Screenshot/Video (IMGUR/YOUTUBE): 
[IMGUR](https://imgur.com/a/bg31HtO)

**Comment by omghixd** [comment]
Removed 4 spawns of this creature in Stormwind City, change will take affect on the 04:00 GMT+1 Maintenance

Thank you for reporting this.
//Fixed and closing this report.

**Comment by dreadnought101** [comment]
They are back 
![Crazed Cultists are back](https://user-images.githubusercontent.com/10070048/101885387-4e7de880-3b57-11eb-94b0-8edd9a8eed05.PNG)
