### ISSUE TITLE
a few quests in hillsbrad

### ISSUE THREAD

**Issue by acidyy** [omghixd/Path-of-Classic-Bugtracker#165]
Quest/Spell/Item/Creature(ID) The ID is: 28138 and 28192

The Current Behaviour is as following: Auto complete

Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by UtilExe** [comment]
Fixed id: 28138. Please report bugs separately.
