### ISSUE TITLE
[Druid][Spell] Thorns does huge damage in Cat Form

### ISSUE THREAD

**Issue by jeffisdrunk** [omghixd/Path-of-Classic-Bugtracker#166]
Quest/Spell/Item/Creature(ID) The ID is: 
http://cata.cavernoftime.com/spell=467

The Current Behaviour is as following: 
Thorn does normal damage in Human Form, but shapeshifting to Cat Form (I haven't tested other forms) gives Thorns x13 more damage. 

Expected Behaviour should be as following: 
Maybe shapeshifting changes the Character's stats in a way that alters damage of current buffs. Check Thorns damage formula maybe?

Screenshot/Video (IMGUR/YOUTUBE): 
https://imgur.com/a/XRMqTTN (first image 15 dmg human form, second is right when i switched to cat form)

Additional Information:

**Comment by jeffisdrunk** [comment]
Tested and the bug works in Bear Form as well

**Comment by omghixd** [comment]
Appreciate the confirmation! :)

**Comment by UtilExe** [comment]
Test on next server update please (probably tomorrow by now)
