### ISSUE TITLE
[Shaman][Spell] Flametongue Weapon deals about x10 times it's normal damage

### ISSUE THREAD

**Issue by jeffisdrunk** [omghixd/Path-of-Classic-Bugtracker#167]
Quest/Spell/Item/Creature(ID) The ID is: 
https://cata.cavernoftime.com/spell=8024
(Link doesn't give full item description for some reason)

The Current Behaviour is as following: 
It just deals huge amounts of damage, all the time.

Expected Behaviour should be as following: 
Damage formula may be altered. Should check.

Screenshot/Video (IMGUR/YOUTUBE): 
No need.

Additional Information:

**Comment by omghixd** [comment]
The high amount of damage is caused by the aura buff [Unleash Flame] https://cata.cavernoftime.com/spell=73683

We will continue to investigate this.

Thank you for reporting.

**Comment by UtilExe** [comment]
Test on next server update please (probably tomorrow by now)
