### ISSUE TITLE
[Quest][An Unwelcome Guest] Bellygrub not 100% quest item drop

### ISSUE THREAD

**Issue by jeffisdrunk** [omghixd/Path-of-Classic-Bugtracker#168]
Quest/Spell/Item/Creature(ID) The ID is: 
http://cata.cavernoftime.com/quest=26509 (Quest)
http://cata.cavernoftime.com/npc=345 (NPC)

The Current Behaviour is as following: 
Quest mob doesn't have 100% quest item drop

Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 
No need.

Additional Information:

**Comment by dreadnought101** [comment]
Can confirm

**Comment by omghixd** [comment]
The quest item is now a 100% drop chance instead of its original 71%.

Thank you for reporting this
//Fixed and closing this report.
