### ISSUE TITLE
Creature - Redridge Mountains : Blackrock Drake

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#17]
Quest/Spell/Item/Creature(ID) The ID is: 43788

The Current Behaviour is as following: See screenshot. Groups of drakes are flying around in circles.

Expected Behaviour should be as following: Groups of drakes should not be flying around in circles like that.

Screenshot/Video (IMGUR/YOUTUBE): 
![image](https://user-images.githubusercontent.com/65196200/98822420-1e94d580-2431-11eb-8a1c-79424b351218.png)

Additional Information:

**Comment by omghixd** [comment]
Cleaned up the area and a lot of redridge mountain. it should be in a much better shape now!

Thank you for reporting this.
//Fixed and Closing this report
