### ISSUE TITLE
[Quest] Nida's Necklace - Glinting Mud

### ISSUE THREAD

**Issue by dreadnought101** [omghixd/Path-of-Classic-Bugtracker#170]
Redridge Mountains -- Its floating rather than on the lakefloor
![Mud floating](https://user-images.githubusercontent.com/10070048/100529223-61310e80-31a2-11eb-8517-98156495810f.PNG)

**Comment by omghixd** [comment]
Fixed that one and the others having similar issues.

Thank you for reporting this.
//Fixed and closing this report.
