### ISSUE TITLE
Creature - Redridge Mountains : Rohh the Silent

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#18]
Quest/Spell/Item/Creature(ID) The ID is: 947

The Current Behaviour is as following: Multiple dupes of him. Killed 4 of this NPC now and there are probably more. He is in stealth so not easy to see. Was found at the gnoll camps below Tower of Ilgalar.

Expected Behaviour should be as following: There should only be 1 of this rare NPC.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Cleaned up the area and a lot of redridge mountain. it should be in a much better shape now!

Thank you for reporting this.
//Fixed and Closing this report
