### ISSUE TITLE
Creature - Duskwood : Zzarc'Vul

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#19]
Quest/Spell/Item/Creature(ID) The ID is: 300

The Current Behaviour is as following: There is a dupe of Zzarc'Vul. There are 2 of this NPC standing close to each other in the ogre cave (37,82) ish.

Expected Behaviour should be as following: There should only be 1 Zzarc'Vul.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Deleted the dupe and gave the surrounding area some life.

Thank you for reporting this.
//Fixed and Closing this report.
