### ISSUE TITLE
Creature - Elwynn Forest : Goldtooth

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#2]
Quest/Spell/Item/Creature(ID) The ID is: 327

The Current Behaviour is as following: Dupe of Goldtooth. There is one of him inside the tunnel where his original position was pre-cata and also one on the hill where his position was in cata.

Expected Behaviour should be as following: Well his position was on top of the hill in Cata but if we are going after a vanilla-feel you could maybe keep the one inside tunnel. Either way, one of them should probably be deleted.

Screenshot/Video (IMGUR/YOUTUBE): 
forgot to take SC when I was inside tunnel.
![image](https://user-images.githubusercontent.com/65196200/98735301-77b62800-23a3-11eb-8a62-278afbbf6ca3.png)

Additional Information:

**Comment by omghixd** [comment]
Dupe inside of the tunnel was removed, the PoI Icon on the map tells us he is at the top of the hill. We shouldn't alter than.

While i was in the tunnel i took the liberty of cleaning it up, seeing how it was a rather big ass mess down there.

Thank you for the report!

//Fixed and closes this report.
