### ISSUE TITLE
Tirisfal, Invisible Rothide Mongrels at Garrens Haunt

### ISSUE THREAD

**Issue by z3nos** [omghixd/Path-of-Classic-Bugtracker#200]
# Invisible Rothide Mongrels at Garrens Haunt

As you can see in the screenshot my felguard killed a mongrel. No corpse to be seen. Multiple mobs on the path are invisible.

![WoWScrnShot_112920_110058](https://user-images.githubusercontent.com/54058776/100538818-40b09500-3232-11eb-8037-7822cc2872bc.jpg)

**Comment by omghixd** [comment]
Some of the Rot Hide Mongrel(s) were spawned half way through the ground. When you load them in they would result in falling through the map and attempt to come back up and would essentially be stuck underground. This **should** no longer be the case. 

Re-open if this issue re-occures =)
Thank you for reporting this.
//Fixed and closing this report.

**Comment by Birdseye123** [comment]
This needs to be reopened. Questing near that field isn't doable right now with the constant deaths lol
