### ISSUE TITLE
[Quest] {Felwood} Dance for Ruumbo!

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#202]
Quest/Spell/Item/Creature(ID) The ID is: 27995

The Current Behaviour is as following: Auto-completed.

Expected Behaviour should be as following: /Dance at the totem(Ruumbo)¨.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/quest=27995/dance-for-ruumbo#

**Comment by UtilExe** [comment]
fixed
