### ISSUE TITLE
[Quest] {Felwood} Hazzard Disposal

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#206]
Quest/Spell/Item/Creature(ID) The ID is: 28213

The Current Behaviour is as following: Auto-complete.

Expected Behaviour should be as following:  Not auto-complete

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/quest=28213/hazzard-disposal

**Comment by UtilExe** [comment]
fixed
