### ISSUE TITLE
[NPC] {Felwood} Shadow Lord Fel'dan - Duplicated Creature

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#207]
Quest/Spell/Item/Creature(ID) The ID is: 28153

The Current Behaviour is as following: Duplicated NPC.

Expected Behaviour should be as following: -

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/quest=28153/shadow-lord-feldan

**Comment by UtilExe** [comment]
fixed
