### ISSUE TITLE
[Quest Item] {Felwood} Infernal Debris "Fel to Pieces", "Infernal-sentry"

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#209]
Quest/Spell/Item/Creature(ID) The ID is: 

The Current Behaviour is as following: Does not drop the quest item.

Expected Behaviour should be as following: Drop the quest item.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
Quest: https://www.wowhead.com/quest=28342/fel-to-pieces
Quest Item: https://www.wowhead.com/item=63123/infernal-debris 
NPC: https://www.wowhead.com/npc=7136/infernal-sentry

**Comment by UtilExe** [comment]
Try on next restart please.
