### ISSUE TITLE
Quest - Mulgore : Our Tribe, Imprisoned

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#21]
Quest/Spell/Item/Creature(ID) The ID is: 
_**24852**_

The Current Behaviour is as following: 
_**You open up the cage and the Captured Brave stays inside**_

Expected Behaviour should be as following: 
_**You open up the cage and the Captured Brave should run out**_

Screenshot/Video (IMGUR/YOUTUBE): 
https://www.youtube.com/watch?v=vehijwC0YfM

Additional Information:

**Comment by UtilExe** [comment]
Fixed
