### ISSUE TITLE
[NPC] {Felwood} Emerald Druid - Tuned incorrectly

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#211]
Quest/Spell/Item/Creature(ID) The ID is: 51610

The Current Behaviour is as following: Incorrectly level tuned

Expected Behaviour should be as following: Tuned accordingly,

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/npc=51610/emerald-druid

**Comment by UtilExe** [comment]
What level should he be?

**Comment by omghixd** [comment]
Neutral mobs in the area was anywhere from 45-57 so i did a sole lvl 50 on this mob.

Thank you for reporting!
//Fixed and closing this report.
