### ISSUE TITLE
[Quest] {Felwood} Slap and Cap

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#214]
Quest/Spell/Item/Creature(ID) The ID is: 28336

The Current Behaviour is as following: Auto-complete.

Expected Behaviour should be as following: Slap 7 Panicked Workers to make them cap the oil gushers. 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/quest=28336/slap-and-cap

**Comment by UtilExe** [comment]
Should be fixed. Lmk if issues.
