### ISSUE TITLE
[Quest] {Felwood} Wisp-napping

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#215]
Quest/Spell/Item/Creature(ID) The ID is: 28370

The Current Behaviour is as following: Auto-complete

Expected Behaviour should be as following: Use Darla's Wisp Magnet to collect 5 Talonbranch Wisps. 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/quest=28370/wisp-napping

**Comment by UtilExe** [comment]
Fixed
