### ISSUE TITLE
[Quest] {Felwood} A Flare Fight

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#216]
Quest/Spell/Item/Creature(ID) The ID is: 28334

The Current Behaviour is as following: Auto-completes

Expected Behaviour should be as following: Use Darla's Box of Megaflares to reveal 8 Talonbranch Prowlers and slay them. 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/quest=28334/a-flare-fight

**Comment by UtilExe** [comment]
Fixed on next update
