### ISSUE TITLE
[Quest Item] {Felwood} It's Time to Oil Up "Quest"

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#217]
Quest/Spell/Item/Creature(ID) The ID is: 63513

The Current Behaviour is as following: Quest Item is usable, however the Object cannot be pulled anywhere and disappears after pulled.

Expected Behaviour should be as following: Can pull the Object to a Irontree shredder and oil it.

Screenshot/Video (IMGUR/YOUTUBE): 
https://youtu.be/Dw0vZ0yjD6s?t=50

Additional Information:
Quest: https://www.wowhead.com/quest=28333/its-time-to-oil-up
Quest Item: https://www.wowhead.com/item=63513/darlas-grapple

**Comment by UtilExe** [comment]
Fixed
