### ISSUE TITLE
[NPC] {Winterspring} Winterfall Runner

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#218]
Quest/Spell/Item/Creature(ID) The ID is: 10916

The Current Behaviour is as following: Standing still.

Expected Behaviour should be as following: Following their pathing route.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/npc=10916/winterfall-runner

**Comment by omghixd** [comment]
Should be fixed now. Re-open the issue if this issue still appears 👍 

//Fixed and closing this report.
