### ISSUE TITLE
[NPC] {Winterspring}Archmage Maenius *Duplicated*

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#223]
Quest/Spell/Item/Creature(ID) The ID is: 48740

The Current Behaviour is as following: Duplicated NPC

Expected Behaviour should be as following: -

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/npc=48740/archmage-maenius

**Comment by omghixd** [comment]
Removed the duplicated NPC

Thank you for reporting this!
//Fixed and closing this report.
