### ISSUE TITLE
[NPC] {Durotar} Raider Jhash

### ISSUE THREAD

**Issue by Birdseye123** [omghixd/Path-of-Classic-Bugtracker#225]
Quest/Spell/Item/Creature(ID) The ID is: 10676

The Current Behaviour is as following: He is not friendly with Horde Characters and attackable.

Expected Behaviour should be as following: He should not be attackable

Screenshot/Video (IMGUR/YOUTUBE): https://imgur.com/a/Ge0SgRy

Additional Information: He should also path along the road to Razor Hill to Sen'Jin Village according to wowhead.
https://classic.wowhead.com/npc=10676/raider-jhash#abilities

**Comment by UtilExe** [comment]
Fixed
