### ISSUE TITLE
[NPC] {Molten Core} Baron Geddon

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#226]
Quest/Spell/Item/Creature(ID) The ID is: 12056

The Current Behaviour is as following: Slow af

Expected Behaviour should be as following: Fast as f boi

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://classic.wowhead.com/npc=12056/baron-geddon

**Comment by UtilExe** [comment]
Try on next server update please
