### ISSUE TITLE
[Quest] Twilight of the dawn runner

### ISSUE THREAD

**Issue by previlin** [omghixd/Path-of-Classic-Bugtracker#250]
Quest/Spell/Item/Creature(ID) The ID is: 
Quest id= 9437
The Current Behaviour is as following: 
Not scripted can't get credit for "Rescue ithania from north point tower 
Expected Behaviour should be as following: 
https://www.youtube.com/watch?v=OMzJsqjzzoE
Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
http://cata.cavernoftime.com/quest=9437

**Comment by UtilExe** [comment]
fixed on next update
