### ISSUE TITLE
[Quest] Stinky's Escape

### ISSUE THREAD

**Issue by previlin** [omghixd/Path-of-Classic-Bugtracker#251]
Quest/Spell/Item/Creature(ID) The ID is: 
id=1270
The Current Behaviour is as following: 
Quest is working but no RP script text form the npc=4880
Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
http://cata.cavernoftime.com/quest=1270

**Comment by UtilExe** [comment]
Should be fixed on next update
