### ISSUE TITLE
[Quest] What's Hauting Witch Hill

### ISSUE THREAD

**Issue by previlin** [omghixd/Path-of-Classic-Bugtracker#252]
Quest/Spell/Item/Creature(ID) The ID is: 
id=27188
The Current Behaviour is as following: 
Set for auto complete. Missing scirpts 
Expected Behaviour should be as following: 
https://www.youtube.com/watch?v=9589UyDsoyM
Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
http://cata.cavernoftime.com/quest=27188

**Comment by UtilExe** [comment]
Fixed
