### ISSUE TITLE
[Quest] Cleansing Witch hill

### ISSUE THREAD

**Issue by previlin** [omghixd/Path-of-Classic-Bugtracker#253]
Quest/Spell/Item/Creature(ID) The ID is: 
id= 11183
The Current Behaviour is as following: 
Set to auto complete. Missing script
Expected Behaviour should be as following: 
https://www.youtube.com/watch?v=8hJEvSkY-ww
Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
http://cata.cavernoftime.com/quest=11183

**Comment by UtilExe** [comment]
Fixed
