### ISSUE TITLE
[NPC] {Orgrimmar} Spirit Healer - Missing

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#256]
Quest/Spell/Item/Creature(ID) The ID is: 6491

The Current Behaviour is as following: Nothing at the orgrimmar point.

Note: Idk if its the correct ID.

Additional Information:
https://www.wowhead.com/npc=6491/spirit-healer

**Comment by omghixd** [comment]
Spawned the Spirit Healer at the appropriate place

Thank you for reporting this.
//Fixed and Closing this report.
