### ISSUE TITLE
[NPC] Apothecary Cylla

### ISSUE THREAD

**Issue by previlin** [omghixd/Path-of-Classic-Bugtracker#257]
Quest/Spell/Item/Creature(ID) The ID is: 
23881
The Current Behaviour is as following: 
Missing loot table. Missing quest item starter http://cata.cavernoftime.com/item=33115
Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
http://cata.cavernoftime.com/npc=23881

**Comment by omghixd** [comment]
This is no longer a quest as of patch 4.0.3. But have been the proper loot-table incase it has loot dependancy for other quests.

Thank you for reporting this.
//Fixed and Closing this report.
