### ISSUE TITLE
[Quest] the essence of enmity

### ISSUE THREAD

**Issue by previlin** [omghixd/Path-of-Classic-Bugtracker#260]
Quest/Spell/Item/Creature(ID) The ID is: 
27409
The Current Behaviour is as following: 
the corpse of the needed NPC for credits does not vanish after you use quest item http://cata.cavernoftime.com/item=33088
Expected Behaviour should be as following: 
Corpse disappears after each use of the quest item  http://cata.cavernoftime.com/item=33088
Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
http://cata.cavernoftime.com/quest=27409

**Comment by omghixd** [comment]
This should now be fixed!

Thank you for reporting this.
//Fixed and Closing this report.
