### ISSUE TITLE
[Quest] Spirits of stonemaul hold

### ISSUE THREAD

**Issue by previlin** [omghixd/Path-of-Classic-Bugtracker#261]
Quest/Spell/Item/Creature(ID) The ID is: 
27410
The Current Behaviour is as following: 
Set to auto complete. Missing script
Expected Behaviour should be as following: 
https://www.youtube.com/watch?v=MJLq0b2FV2U
Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
http://cata.cavernoftime.com/quest=27410

**Comment by omghixd** [comment]
This should now be fixed!

Thank you for reporting this.
//Fixed and Closing this report.
