### ISSUE TITLE
 [Quest] {Darkshore} Threat from the Water

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#266]
Quest/Spell/Item/Creature(ID) The ID is: 13522

The Current Behaviour is as following: Auto-complete.

Expected Behaviour should be as following:  Not auto-complete

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/quest=13522/threat-from-the-water

**Comment by omghixd** [comment]
This should now be fixed!

Thank you for reporting this.
//Fixed and Closing this report.
