### ISSUE TITLE
 [Quest] {Darkshore} Unsavory Remedies

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#269]
Quest/Spell/Item/Creature(ID) The ID is: 13598

The Current Behaviour is as following: Auto-complete.

Expected Behaviour should be as following: Not Auto-complete.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/quest=13598/unsavory-remedies

**Comment by omghixd** [comment]
This should now be fixed!

Thank you for reporting this.
//Fixed and Closing this report.
