### ISSUE TITLE
Quest - Mulgore : The Restless Earth

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#27]
Quest/Spell/Item/Creature(ID) The ID is: 
_**14491**_

The Current Behaviour is as following: 
_**Use  quest item (49647) on creature (36845) it counts towards the quest but it does not enact the script**_

Expected Behaviour should be as following: 
_**Use the quest item (49647) on creature (36845) it should make the earth spirit come towards you and either become friendly and dissapair or become hostile and attack you. When it becomes friendly only then it should count towards the quest**_

Screenshot/Video (IMGUR/YOUTUBE): 
https://gyazo.com/a768b863551a055b058940a8e5dc28ea

Additional Information:
**_The quest item used (49647) is useable on every npc / creature / player in the game, no matter where you are. Unless there is a zone restriction on the quest item_**
_**In my experience this is the case with every quest item with a "use" ability on it. This is highly abuseable!!!!!!!!**_

https://gyazo.com/9413ea1aac202d02e09cbc5cc280a1eb

https://gyazo.com/cf1f363e9ae10feccdc40b09b46f4cd6

**Comment by UtilExe** [comment]
Fixed
