### ISSUE TITLE
[Quest] {Darkshore} Remembrance of Auberdine 

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#273]
Quest/Spell/Item/Creature(ID) The ID is: 13570

The Current Behaviour is as following: Grey quest u you can turn in at the NPC without picking anything up.

Expected Behaviour should be as following: Function properly.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/quest=13570/remembrance-of-auberdine

**Comment by omghixd** [comment]
This quest actually does not have any objectives. And is suppose to be an auto-complete! 

However it was missing some text. That was added back in the game.

Thank you for reporting this!
//Fixed and Closing this report.
