### ISSUE TITLE
Quest: Counterattack!

### ISSUE THREAD

**Issue by OxyImmortal** [omghixd/Path-of-Classic-Bugtracker#282]
**Quest/Spell/Item/Creature(ID) The ID is:** 4021

**The Current Behaviour is as following:** 
After killing the required elite, the banner spawns, but is unclickable.
Became interactable after 3-4 minutes - unknown if it was just a timer issue or something else.

**Expected Behaviour should be as following:** 
After elite is dead, and banner spawns, should be clickable.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
The object will no longer spawn and the item will instead be looted from Warlord Krom'zar. 

Thank you for reporting this.
//Fixed and Closing this report.
