### ISSUE TITLE
Quest: Mor'shan Defense!

### ISSUE THREAD

**Issue by OxyImmortal** [omghixd/Path-of-Classic-Bugtracker#283]
**Quest/Spell/Item/Creature(ID) The ID is:** 13612

**The Current Behaviour is as following:** 
Mobs required do not spawn and/or are instantly killed by the guards they are supposed to ''fight''
Leads to quest being impossible to complete.

**Expected Behaviour should be as following:** 
Mobs should spawn and engage in combat with the guards and SLOWLY die.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
This area has been redesigned and the quest should now be completable. Also added several creature walking around in the area and some that walk towards the camp to assault it.

Thank you for reporting this!
//Fixed and Closing this report.
