### ISSUE TITLE
Quest - Elwynn Forest : Goldtooth

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#3]
Quest/Spell/Item/Creature(ID) The ID is: 87
Quest/Spell/Item/Creature(ID) item=981

The Current Behaviour is as following: Bernice's Necklace does not have 100% drop chance. Killed both the Goldtooth within the mine and the one on the hill and neither of them dropped it.

Expected Behaviour should be as following: Bernice's Necklace should have a 100% drop chance.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Item [Bernie's Necklace]:981 now has a 100% drop chance to drop from creature [Goldtooth]:327

// Fixes and closes this report.
