### ISSUE TITLE
Creature - Mulgore : The Rake

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#32]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[5807](https://cata-twinhead.twinstar.cz/?npc=5807)_**

The Current Behaviour is as following: 
**_This creature has multiple spawns at the same time_**

Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Can you specify where this happens? Very little information on where this NPC is located.

**Comment by mikedej** [comment]
Between Camp Sungraze and Red Rocks

**Comment by omghixd** [comment]
Thank you, Found it.

Removed all spawns and re-added a fresh one. I also gave it the pathing it is suppose to have

//Fixes and closes this report
