### ISSUE TITLE
Creature - Mulgore : Bristleback Interloper

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#33]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[3232](https://cata-twinhead.twinstar.cz/?npc=3232)_**

The Current Behaviour is as following: 

Expected Behaviour should be as following: 
**_This creature should not drop quest item [4751](https://cata-twinhead.twinstar.cz/?item=4751)_**

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
This creature no longer drops this item.

//Fixes and closes this report.
