### ISSUE TITLE
Creature - Mulgore : Flatland Prowler

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#34]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[3566](https://cata-twinhead.twinstar.cz/?npc=3566)_**

The Current Behaviour is as following: 
**_This creature is in stealth. When you aggro it, it comes towards you but VERY slowly_**

Expected Behaviour should be as following:
**_Overall speed should be increased a bit_** 
**_Quest item [5203](https://cata-twinhead.twinstar.cz/?item=5203) should only drop when you have the quest at a 90% drop chance_**

Screenshot/Video (IMGUR/YOUTUBE):
**_Speed whilst in stealth: https://gyazo.com/ad27cb6e7c93712b8ea3a2b8f4799649_** 

**_Speed whilst out stealth https://gyazo.com/aa551888483c1b47f3cd8c542ba16730_**

Additional Information:

**Comment by omghixd** [comment]
Speed was increased to 100% when out of stealth and with proper modifiers when its in stealth mode.

and the item will have a drop chance of 85% instead of its original rate of 35%.

//Fixes and closes this report
