### ISSUE TITLE
Quest - Mulgore : Swoop Hunting

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#35]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[761](https://cata-twinhead.twinstar.cz/?quest=761)_**

The Current Behaviour is as following: 

Expected Behaviour should be as following:
**_Quest item [4769](https://cata-twinhead.twinstar.cz/?item=4769) should have a 100% drop chance on the following creatures:_**
 
**_Creature [2969](https://cata-twinhead.twinstar.cz/?npc=2969)_** 
**_Creature [2970](https://cata-twinhead.twinstar.cz/?npc=2970)_** 
**_Creature [2971](https://cata-twinhead.twinstar.cz/?npc=2971)_**  

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Drop rate is now 100% for creatures 2969, 2970 and 2971.

//Fixes and closes this report

**Comment by omghixd** [comment]
Also removed data suggesting other mobs has a drop chance for this item. Even tho they shouldn't have it.
