### ISSUE TITLE
Quest - Mulgore : Kyle's Gone Missing!

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#36]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[11129](https://cata-twinhead.twinstar.cz/?quest=11129)_**

The Current Behaviour is as following:
**_On accepting this quest it auto completes_** 
**_[Kyle the Frenzied](https://cata-twinhead.twinstar.cz/?npc=23616) has a fixed spawnpoint, and doesn't run around Bloodhoof Village_**

Expected Behaviour should be as following:
**_You have to kill any plainstrider creature and loot quest item [33009](https://cata-twinhead.twinstar.cz/?item=33009)_**
**_Then you have to find [Kyle the Frenzied](https://cata-twinhead.twinstar.cz/?npc=23616) who is supposed to have a circle of waypoints througout Bloodhoof Village_**
**_Then you use the quest item near him, which should lure him to the food and eat it. This results in him becoming [Kyle the Friendly](https://cata-twinhead.twinstar.cz/?npc=23622) and it completes the quest_**

Screenshot/Video (IMGUR/YOUTUBE): 
**_https://www.youtube.com/watch?v=2ssDhVZRCGk_**

Additional Information:

**Comment by omghixd** [comment]
Gave the wolf the waypoints it is suppose to have and it now paths around. Will make sure he runs and rescript the quest at a later point.

**Comment by mikedej** [comment]
I made a report before about Kyle having atleast 1 duplicate at the village

**Comment by UtilExe** [comment]
Fixed
