### ISSUE TITLE
Quest - Mulgore : War Dance

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#37]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[24540](https://cata-twinhead.twinstar.cz/?quest=24540)_**

The Current Behaviour is as following:

Expected Behaviour should be as following: 
**_When you engage [Orno Grimtotem](https://cata-twinhead.twinstar.cz/?npc=36931), Baine Bloodhoof should spawn and engage in the fight with you. Also when Baine spawns 2 [Grimtotem Ambusher's](https://cata-twinhead.twinstar.cz/?npc=37062) should spawn to attack Baine_**
_**Check their script / spells / loretext**_

**_When you enter the Grimtotem base, the [Grimtotem Defender's](https://cata-twinhead.twinstar.cz/?npc=37178) and [Thunder Bluff Brave's](https://cata-twinhead.twinstar.cz/?npc=37175) should be engaged in combat_** 

Screenshot/Video (IMGUR/YOUTUBE): 
**_https://www.youtube.com/watch?v=XFoiibyde_Q_**

Additional Information:

_**In the Grimtotem base, there are a few Windfury and Couger creatures hoovering under ground. They will aggro you, but not come up unless you move**_

**Comment by UtilExe** [comment]
Should be much better now.
There's some small visual issues, including some timing that is incorrect, but I consider the state good now.
