### ISSUE TITLE
Badlands - Duplicate spawn

### ISSUE THREAD

**Issue by itzhobbes2** [omghixd/Path-of-Classic-Bugtracker#374]
Quest/Spell/Item/Creature(ID) The ID is: "baelog" (460800) @ 20.48, 46.57

The Current Behaviour is as following: Duplicate spawn

Additional Information: https://www.wowhead.com/npc=46856/baelog

**Comment by omghixd** [comment]
Dupe has been cleared up and the zone has been briefly cleaned up.

Thank you for reporting this!
//Fixed and Closing this report.
