### ISSUE TITLE
Quest - Northern Barrens : Plainstrider Menace

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#38]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[844](https://cata-twinhead.twinstar.cz/?quest=844)_**

The Current Behaviour is as following: 

Expected Behaviour should be as following: 
**_This [quest item](https://cata-twinhead.twinstar.cz/?item=5087) should have the following drop rates:_**

**_Creature [3244](https://cata-twinhead.twinstar.cz/?npc=3244): 75%_**
**_Creature [3245](https://cata-twinhead.twinstar.cz/?npc=3245): 75%_**
**_Creature [3246](https://cata-twinhead.twinstar.cz/?npc=3246): 75%_**

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Drop rates are now 75% instead of 35%, 45% and 50%.

//Fixes and closes this report
