### ISSUE TITLE
Creature - Northern Barrens : Kranal Fiss

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#40]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[5907](https://cata-twinhead.twinstar.cz/?npc=5907)_**

The Current Behaviour is as following:
**_This creature is spawned double_**

Expected Behaviour should be as following: 
_**Only the one infront of the inn should be spawned**_

Screenshot/Video (IMGUR/YOUTUBE): 
**_https://gyazo.com/69036957a76a3ffd0e7230cbb4ce3a53_**

Additional Information:

**Comment by omghixd** [comment]
Removed dupe near the house.

//Fixes and closes this report
