### ISSUE TITLE
Creature - Northern Barrens : Innkeeper Kerntis

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#41]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[43946](https://cata-twinhead.twinstar.cz/?npc=43946)_**

The Current Behaviour is as following: 
**_When talking to her, she offers the line "I want to browse your goods" twice_**

Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE):
**_https://gyazo.com/8b275122c9c4ef73d8564261a3158fd9_** 

Additional Information:

**Comment by omghixd** [comment]
Removed both duplicate options of "I want to brose your goods" and "Make this inn your home."

//Fixes and closes this report.
