### ISSUE TITLE
Quest - Northern Barrens : Drag it Out of Them

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#42]
Quest/Spell/Item/Creature(ID) The ID is:
**_[13961](https://cata-twinhead.twinstar.cz/?quest=13961)_** 

The Current Behaviour is as following:
**_This quest auto completes_** 
**_I tried to use the [quest item](https://cata-twinhead.twinstar.cz/?item=46722) anyway, but it didn't work_**

Expected Behaviour should be as following:
**_You have to bring a [Razormane Pillager](https://cata-twinhead.twinstar.cz/?npc=34503) down in health till the point he starts running away from you. This is when you use the [quest item](https://cata-twinhead.twinstar.cz/?item=46722) on him_** 
**_This is when he turns friendly and he gives you a chat option saying "Pound this chump". When you click on this option you should drag him behind you with a rope._**
**_When you drag him in range of the [quest giver](https://cata-twinhead.twinstar.cz/?npc=34513), the quest should complete itself_**
**_Check if the [Razormane Pillager](https://cata-twinhead.twinstar.cz/?npc=34503) disappears if you get in range of the quest giver, or if you complete the quest_**

Screenshot/Video (IMGUR/YOUTUBE): 
**_https://www.youtube.com/watch?v=VdrViB3AHLk_**

Additional Information:
**_The [quest item](https://cata-twinhead.twinstar.cz/?item=46722) is useable on every creature / npc / player, no matter where you are in the world (unless it's bound by a zone restriction)_**

**Comment by UtilExe** [comment]
Should be heavily improved now.
