### ISSUE TITLE
Quest - Northern Barrens : By Hook or By Crook

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#43]
Quest/Spell/Item/Creature(ID) The ID is:
**_[13963](https://cata-twinhead.twinstar.cz/?quest=13963)_** 

The Current Behaviour is as following: 
**_This quest auto completes_**
**_The [Captured Razormane's ](https://cata-twinhead.twinstar.cz/?npc=34523) chat options are not working_**

Expected Behaviour should be as following: 
**_The [Captured Razormane](https://cata-twinhead.twinstar.cz/?npc=34523) should be chained to the fence
Also his chat option's should have the correct response in emote, script and text, also he should give you buffs depending on what option you click_**
**_I suppose after you click 2 or 3 different options the quest should complete_**

Screenshot/Video (IMGUR/YOUTUBE): 
**_https://www.youtube.com/watch?v=mELAwcDId5Q_**

Additional Information:

**Comment by UtilExe** [comment]
Fixed
