### ISSUE TITLE
Desolace- Two 'Christi Galvanis' NPCs

### ISSUE THREAD

**Issue by dreadnought101** [omghixd/Path-of-Classic-Bugtracker#439]
Remove the one in the corner marked in red.
![Two Christi Galvanis](https://user-images.githubusercontent.com/10070048/101094676-028cdb80-357a-11eb-92ee-9e3ede8adc54.PNG)

**Comment by omghixd** [comment]
The dupe has been cleared and the blue one insteads paths around to fill the room gap.

Thank you for reporting this.
//Fixed and Closing this report.
