### ISSUE TITLE
Quest - Northern Barrens : The Kodo's Return

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#44]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[13971](https://cata-twinhead.twinstar.cz/?quest=13971)_**

The Current Behaviour is as following:
**_Upon accepting the quest it completes but nothing happens with the kodo_** 

Expected Behaviour should be as following: 
**_Upon accepting the quest the [kodo](https://cata-twinhead.twinstar.cz/?npc=34547) should stand up and start walking towards Grol'dom Farm. At this point the quest is already completed. After a while he should just dissapair. He doesn't have to walk all the way to the farm, since it's not an escort quest_**

Screenshot/Video (IMGUR/YOUTUBE): 
**_https://www.youtube.com/watch?v=HVMauz8tQQ0_**

Additional Information:

**Comment by UtilExe** [comment]
Fixed, but one visual issue when the kodo moves. Looks like a core issue. Will try to look later
