### ISSUE TITLE
Desolace- level 85 guards at Nijel's Point

### ISSUE THREAD

**Issue by dreadnought101** [omghixd/Path-of-Classic-Bugtracker#440]
"Nijel's Point Guard"  Most guards should be level 40 but some are level 85.
1
![Nijel's Point Guard 1](https://user-images.githubusercontent.com/10070048/101095698-8f846480-357b-11eb-919f-fd229f386da8.PNG)
these 3
![Nijels Point Gaurd 2](https://user-images.githubusercontent.com/10070048/101095705-91e6be80-357b-11eb-9552-87bf953c614c.PNG)
1
![Nijel's Point Guard 3](https://user-images.githubusercontent.com/10070048/101095710-94491880-357b-11eb-8f8e-f2bd3cb6b5e7.PNG)
1
![Nijels point guard 4](https://user-images.githubusercontent.com/10070048/101095719-9612dc00-357b-11eb-9256-df5ad199e794.PNG)

**Comment by omghixd** [comment]
Removed all of the lvl 85 Guards from the Area and replaced with lower level Guards.

Thank you for reporting this
//Fixed and Closing this report.
