### ISSUE TITLE
Desolace- Nijel's point duplicate NPCs

### ISSUE THREAD

**Issue by dreadnought101** [omghixd/Path-of-Classic-Bugtracker#441]
x2 of these two types
![Duplicate NPCs Nijel's Point](https://user-images.githubusercontent.com/10070048/101095092-a1b1d300-357a-11eb-8f58-9d997b80be6d.PNG)

**Comment by dreadnought101** [comment]
Also the inkeeper has no hearthstone capabilities

**Comment by omghixd** [comment]
The two dupes have been cleared and the inkeeper is able to set your hearthstone to Nijel's Point now.

Thank you for reporting this
//Fixed and Closing this report.
