### ISSUE TITLE
Desolace- Dead Brother Anton in wrong location

### ISSUE THREAD

**Issue by dreadnought101** [omghixd/Path-of-Classic-Bugtracker#442]
This NPC should be dead as of cataclysm, but should be placed in valley of bones, but is in Nijel's Point.

Coords SHOULD BE -- 62.0, 91.2

https://www.wowhead.com/npc=1182/brother-anton

![Dead Brother Anton](https://user-images.githubusercontent.com/10070048/101096067-3bc64b00-357c-11eb-8dd2-0d5cfcf15227.PNG)

**Comment by omghixd** [comment]
Removed him from Nijel's Point and checked the Cords you gave. Hes here and dead.

Thank you for reporting this.
//Fixed and Closing this report.
