### ISSUE TITLE
Desolace- Nijel's point- Flammable Tree Stalker? 

### ISSUE THREAD

**Issue by dreadnought101** [omghixd/Path-of-Classic-Bugtracker#443]
what is this.  Don't know what its doing there and don't know if its a trigger NPC for some type of event of animation, but feels wrong.

![Flammable tree stalker](https://user-images.githubusercontent.com/10070048/101096521-e8083180-357c-11eb-8a1e-5f0ee3ebd4fd.PNG)

**Comment by omghixd** [comment]
They have been cleared from the area along with other trigger NPCs that are not really suppose to be there. The area is also cleaned up and should appear in a much better state.

Thank you for reporting this
//Fixed and Closing this report.
