### ISSUE TITLE
Ironforge auction house is...screwd up

### ISSUE THREAD

**Issue by dreadnought101** [omghixd/Path-of-Classic-Bugtracker#455]
Its just 1 goblin, and its linked to the neutral AH

![Ironforge Auction house](https://user-images.githubusercontent.com/10070048/101112074-c8333680-3599-11eb-89e8-b5670126e267.PNG)

**Comment by omghixd** [comment]
It is intended to be linked to the Neutral AH. As suggested by the community when this was implemented. Will correct the positioning tho as he has fallen through the barrel instead of standing on-top of it.

Thank you for reporting this
//Fixed and Closing this report.
