### ISSUE TITLE
Desolace- Infernal markers and floating Hyenas

### ISSUE THREAD

**Issue by dreadnought101** [omghixd/Path-of-Classic-Bugtracker#469]
All in 1 screenshot at coords 40.0, 39.3 in desolace.

![Infernal Marks and floating Hyenas](https://user-images.githubusercontent.com/10070048/101148248-a312e800-35da-11eb-9373-ed1f7af9efe2.PNG)

**Comment by dreadnought101** [comment]
More infernal markers in this local area (coords taken at 44.3, 44.5)

![Infernal markers more in Desolace](https://user-images.githubusercontent.com/10070048/101148673-2cc2b580-35db-11eb-9f3c-9948c7f7fab4.PNG)

**Comment by omghixd** [comment]
This should be fixed.

Thank you for reporting this!
//Fixed and Closing this report.
