### ISSUE TITLE
[Quest] {Western Plaguelands} - "Araj the Summoner"

### ISSUE THREAD

**Issue by itzhobbes2** [omghixd/Path-of-Classic-Bugtracker#473]
**Quest/Spell/Item/Creature(ID) The ID is:** 

(Quest ID) 27164
https://www.wowhead.com/quest=27164/araj-the-summoner#videos

**The Current Behaviour is as following:** 

_**My Recording:**_
https://youtu.be/gQZzv6Qz81s

You are able to collect the quest item (object id) 17114 before killing (creature id) 474112

**Expected Behaviour should be as following:** 

You should need to slay (creature id) 474112 before being able to interact with the quest objective and collecting (object id) 17114

**_Reference Video:_**
https://youtu.be/gQZzv6Qz81s

----

**The Current Behaviour is as following:** 

Turning in quest to NPC 894208 results in no quest text.

**Expected Behaviour should be as following:** 

**_Quest text should be as follows :_**

"Araj dead... this is good.  That gnome has done his part in winning this war.  As have you, < name >."

**Comment by omghixd** [comment]
The crystal will no longer be loot-able but will spawn as a visual effect when Araj dies and Araj will instead drop the item on death.

Thank you for reporting this.
//Fixed and Closing this report
