### ISSUE TITLE
[Quest] {Western Plaguelands} - "Brute Stength"

### ISSUE THREAD

**Issue by itzhobbes2** [omghixd/Path-of-Classic-Bugtracker#474]
**Quest/Spell/Item/Creature(ID) The ID is:** 

(Quest ID) 27163
https://www.wowhead.com/quest=27163/brute-strength

**The Current Behaviour is as following:** 

Turning in quest to NPC 894208 results in no quest text.

**Expected Behaviour should be as following:** 

**_Quest text should be as follows:_**

"Excellently done, < name >."

**Comment by omghixd** [comment]
Added completion text.

Thank you for reporting this.
//Fixed and Closing this report
