### ISSUE TITLE
[Misc] {Western Plaguelands} - Not sure what this is

### ISSUE THREAD

**Issue by itzhobbes2** [omghixd/Path-of-Classic-Bugtracker#475]
**Quest/Spell/Item/Creature(ID) The ID is:** 

ID 584512

**The Current Behaviour is as following:** 

Not sure what this is. 

![WoWScrnShot_120420_064631](https://user-images.githubusercontent.com/66154417/101171371-e1b99a00-35fc-11eb-8f36-2efc468759af.jpg)

**Comment by omghixd** [comment]
These should no longer be visible. They are Trigger NPCs

Thank you for reporting this
//Fixed and Closing this report.
