### ISSUE TITLE
[Quest] {Western Plaguelands} - "Victory, For Now"

### ISSUE THREAD

**Issue by itzhobbes2** [omghixd/Path-of-Classic-Bugtracker#478]
**Quest/Spell/Item/Creature(ID) The ID is:** 
(Quest ID) 27165
https://www.wowhead.com/quest=27165/victory-for-now#see-also

**The Current Behaviour is as following:** 

Turning in quest to NPC 677376 results in no quest text.

**Expected Behaviour should be as following:** 

**_Quest text should be as follows:_**

"Word arrived shortly before you did, <name>.  With the Scourge ejected from Andorhal, we are one step closer to retaking Lordaeron."

**Comment by omghixd** [comment]
This should now be working as intentional.

Thank you for reporting this.
//Fixed and Closing this report.
