### ISSUE TITLE
[Object] {Ashenvale} Herb underground - Lake Falathim

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#479]
![herb misssing](https://user-images.githubusercontent.com/51031522/101193989-a7ccb000-365d-11eb-8484-75ec9d7a9ebe.PNG)
![herb missing 1](https://user-images.githubusercontent.com/51031522/101194008-abf8cd80-365d-11eb-9c8a-59d2864bfb1c.PNG)

**Comment by omghixd** [comment]
Underground spawn has been removed.

Thank you for reporting this.
//Fixed and Closing this report.
