### ISSUE TITLE
NPC in Gadgetzan Agro

### ISSUE THREAD

**Issue by Partycles** [omghixd/Path-of-Classic-Bugtracker#483]
![image](https://user-images.githubusercontent.com/75519680/101237969-36096a80-3720-11eb-98df-25f68acfb606.png)

I have a pet but its on passive so idk why the NPC is getting agro on it

**Comment by omghixd** [comment]
This creature will no longer attack hunter(s) pet(s)

Thank you for reporting this.
//Fixed and Closing this report.
