### ISSUE TITLE
NPC Silva Fil'naveth missing

### ISSUE THREAD

**Issue by dreadnought101** [omghixd/Path-of-Classic-Bugtracker#492]
Should be in this location (was here previously a day ago), but now missing, including /target searches.

![Silva Fil'naveth missing](https://user-images.githubusercontent.com/10070048/101338790-b1f7d580-383a-11eb-93e4-fc71e9330c94.PNG)

**Comment by omghixd** [comment]
Creature has been added.

Thank you for reporting this!
//Fixed and Closing this report.
