### ISSUE TITLE
Spirit healer missing

### ISSUE THREAD

**Issue by previlin** [omghixd/Path-of-Classic-Bugtracker#496]
Quest/Spell/Item/Creature(ID) The ID is: 
6491
The Current Behaviour is as following: 
Missing spirit healer at durotar orc/troll starting zone
Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 
https://imgur.com/4oqbR4a
Additional Information:
https://www.wowhead.com/npc=6491/spirit-healer

**Comment by omghixd** [comment]
Spawned the missing Spirit Healer

Thank you for reporting this!
//Fixed and Closing this report.
