### ISSUE TITLE
Quest - Elwynn Forest : Wanted: "Hogger"

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#5]
Quest/Spell/Item/Creature(ID) The ID is: 176

The Current Behaviour is as following: The NPCs in the screenshot are just standing there permanently.

Expected Behaviour should be as following: Those NPCs should appear after you kill Hogger where RP starts. Not a super big deal though.

Screenshot/Video (IMGUR/YOUTUBE): 
![image](https://user-images.githubusercontent.com/65196200/98741508-15622500-23ad-11eb-94eb-5102b416674a.png)

Additional Information:

**Comment by omghixd** [comment]
Removed the static creatures. RP has been disabled as of right now, but the code is present.

//Fixes and closes this report.
