### ISSUE TITLE
Creature [Stonetalon Mountains] {Barshuk Heavyhammer}

### ISSUE THREAD

**Issue by Birdseye123** [omghixd/Path-of-Classic-Bugtracker#519]
Quest/Spell/Item/Creature(ID) The ID is: https://cata-twinhead.twinstar.cz/?npc=41890

The Current Behaviour is as following: He sells a quest item from scholazar basin called Freya's Horn. Not usable but still weird.

Expected Behaviour should be as following: He shouldn't sell it.

Screenshot/Video (IMGUR/YOUTUBE): blob:https://imgur.com/fbf90b05-a085-4c58-a3f7-99f779541a64

Additional Information:

**Comment by omghixd** [comment]
The vendor no longer sells this item.

Thank you for reporting this!
//Fixed and Closing this report.
