### ISSUE TITLE
[NPC] geologist-larksbane

### ISSUE THREAD

**Issue by previlin** [omghixd/Path-of-Classic-Bugtracker#521]
Quest/Spell/Item/Creature(ID) The ID is: 
id= 15183
The Current Behaviour is as following: 
MIA in silithus 
Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/npc=15183/geologist-larksbane

**Comment by omghixd** [comment]
NPC has been spawned in Cenarion Hold (Silithus)

Thank you for reporting this.
//Fixed and Closing this report.
