### ISSUE TITLE
Quest - Northern Barrens : Echeyakee

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#59]
Quest/Spell/Item/Creature(ID) The ID is:
**_[881](https://cata-twinhead.twinstar.cz/?quest=881)_** 

The Current Behaviour is as following: 
**_[Echeyakee](https://cata-twinhead.twinstar.cz/?npc=3475) is already spawned at "Echeyakee's Lair"_**
**_The [quest item](https://cata-twinhead.twinstar.cz/?item=10327) doesn't work_**

Expected Behaviour should be as following:
**_You have to go to "Echeyakee's Lair" (Coords 45, 48), use the [quest item](https://cata-twinhead.twinstar.cz/?item=10327)
This should spawn [Echeyakee](https://cata-twinhead.twinstar.cz/?npc=3475)_** 

Screenshot/Video (IMGUR/YOUTUBE):
**_https://www.youtube.com/watch?v=9I6W5ps0JLw_** 

Additional Information:

**Comment by UtilExe** [comment]
Fixed
