### ISSUE TITLE
Quest - Westfall : Murder Was The Case That They Gave Me

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#6]
Quest/Spell/Item/Creature(ID) The ID is: 26209

The Current Behaviour is as following: For 2 of the Transients nothing happens when you interact with them (ask them who killed the furbolgs or offer them copper). Also, the number of transients is quite low and their respawn time is definitely way too high.

Expected Behaviour should be as following: Transients should always choose to fight or give a clue. Their respawn time should also be lower.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
Quest is such a pain in the ass to do right now since you have to wait so long due to respawn time.

**Comment by UtilExe** [comment]
Reworked the entire quest, works much better now. Also, fixed the high respawn timer.
