### ISSUE TITLE
Creature - Northern Barrens : Eroded Anubisath Warbringer

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#61]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[15810](https://cata-twinhead.twinstar.cz/?npc=15810)_**

The Current Behaviour is as following: 

Expected Behaviour should be as following:
**_I found a few of these creatures scattered around Northern / Southern Barrens.
I believe these creatures should only be  spawning during the opening of the Gates of Ahn'Qiraj event._** 

Screenshot/Video (IMGUR/YOUTUBE): 
**_https://gyazo.com/41eb1c1fb17160f493e7b4e4f6838e4f_**

Additional Information:
**_This one is found at coords 58 / 70_**

**Comment by omghixd** [comment]
These were removed and scheduled to be respawned when said event takes place.


//Closes and fixes this report
