### ISSUE TITLE
Creature - Northern Barrens : Gazrog

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#62]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[3464](https://cata-twinhead.twinstar.cz/?npc=3464)_**

The Current Behaviour is as following: 
**_He's currently spawned in Crossroads (49 / 59) and Ratchet (67 / 73)_**

Expected Behaviour should be as following:
**_He should only be spawned in Ratchet (67 / 73)_** 
**_He's holding his axe like he's holding a gun (see picture below)_**

Screenshot/Video (IMGUR/YOUTUBE):
**_https://gyazo.com/0341fed81d08da13b12f55727e448b6a_** 

Additional Information:

**Comment by omghixd** [comment]
Removed the Gazrog spawn in Crossroads and Gazrog in Ratchet no longer holds his sword as a gun.

//Fixes and closes this report
