### ISSUE TITLE
Item - Northern Barrens : Altered Snapjaw Shell

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#63]
Quest/Spell/Item/Creature(ID) The ID is:
**_[5098](https://cata-twinhead.twinstar.cz/?item=5098)_** 

The Current Behaviour is as following: 

Expected Behaviour should be as following:
**_This item should have the following drop rate:_** 

**_[3461](https://cata-twinhead.twinstar.cz/?npc=3461) 100%_**

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Item now has a drop rate of 100% instead of its original 73%

//Fixes and closes this report
