### ISSUE TITLE
Creature - Northern Barrens : Tonga Runtetotem

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#64]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[3448](https://cata-twinhead.twinstar.cz/?npc=3448)_**

The Current Behaviour is as following:
**_This creature is currently spawned twice in The Crossroads_** 
**_Coords are 50.0 / 61.5 and 49.5 / 58.7_**

Expected Behaviour should be as following: 
**_He should only be spawned at 49.5 / 58.7_**

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
The Dupe has been deleted.

//Fixes and closes this report
