### ISSUE TITLE
Creature - Northern Barrens : Peon

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#65]
Quest/Spell/Item/Creature(ID) The ID is:
**_[14901](https://cata-twinhead.twinstar.cz/?npc=14901)_** 

The Current Behaviour is as following: 
**_This cave at coords 58.6 / 63.1 has alot of death peons in and around it_** 

Expected Behaviour should be as following:
**_Shouldn't they be alive and do some working animations_** 

Screenshot/Video (IMGUR/YOUTUBE):
**_https://gyazo.com/df7bda7b779668702313e4055cc96fc6_** 

Additional Information:

**Comment by omghixd** [comment]
Removed dead ones and replaced them with alive ones which also has a small animation.

//Fixes and closes this report
