### ISSUE TITLE
Creature - Northern Barrens: Sunscale Ravager

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#68]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[44164](https://cata-twinhead.twinstar.cz/?npc=44164)_**

The Current Behaviour is as following: 
**_When I pull this creature it makes my character say a weird text: "MERR text message!"_**
**_See gif below_**

Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE):
**_https://gyazo.com/61286dc0c7b1572720939d590999de16_** 

Additional Information:

**Comment by omghixd** [comment]
Lol! That was actually me screwing around with Smart Scripts the other day. I've removed this.

//Fixes and closes this report
