### ISSUE TITLE
Quest - Westfall : Feast or Famine

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#7]
Quest/Spell/Item/Creature(ID) The ID is: 26230

The Current Behaviour is as following: The vast majority of Dirt Piles do not give a Fresh Dirt item.

Expected Behaviour should be as following: Dirt Piles should always give 1 Fresh Dirt.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Gave the item a 100% drop chance instead of its original 25%. 

Also spawned a few more Dirt Piles as i can recall there being far more than what was present at that location.

//Fixes and closes this report.
