### ISSUE TITLE
Creature - Northern Barrens : Swiftmane

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#70]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[5831](https://cata-twinhead.twinstar.cz/?npc=5831)_**

The Current Behaviour is as following: 
**_This rare is currently spawned (atleast) twice. Coords are 64.3 / 59.6 and 66.0 / 65.0_**
**_His spawntime is quite fast, i'd say about 5 minutes_**

Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
_**I think spawn time on rares is just fast overall, perhaps you can check this**_

**Comment by omghixd** [comment]
Dupe was removed and the remaining rare was given a 900s respawntimer (15 minutes)

//Fixes and closes this report
