### ISSUE TITLE
Quest - Northern Barrens : Club Foote

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#72]
Quest/Spell/Item/Creature(ID) The ID is:
**_[14034](https://cata-twinhead.twinstar.cz/?quest=14034)_** 

The Current Behaviour is as following: 
**_On accepting this quest, the [quest item](https://cata-twinhead.twinstar.cz/?item=46827) appears in your bag and completes the quest_**

Expected Behaviour should be as following:
**_You should get the quest item yourself by doing the quest, because it actually works just fine_** 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by UtilExe** [comment]
Fixed
