### ISSUE TITLE
Creature - Northern Barrens : Theramore Deck Hand

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#73]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[34707](https://cata-twinhead.twinstar.cz/?npc=34707)_**

The Current Behaviour is as following: 
**_This creature is friendly towards Horde_**

Expected Behaviour should be as following: 
**_This creature should be hostile towards Horde, but Friendly towards Alliance_**

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Theramore Deck Hand is now friendly to the Alliance and Hostile towards the Horde.

//Fixes and closes this report

**Comment by mikedej** [comment]
@ the Merchant Coast the Deck Hands are still friendly to me as horde.

**Comment by omghixd** [comment]
A server restart was required for that change to affect. So i would suggest re-checking it now.
