### ISSUE TITLE
Creature - Northern Barrens : Southsea Cannoneer

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#75]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[3382](https://cata-twinhead.twinstar.cz/?npc=3382)_**

The Current Behaviour is as following: 
**_This creature is neutral towards Horde_**

Expected Behaviour should be as following: 
**_This creature should be hostile towards Horde_**

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Creature is now hostile towards the Horde

//Fixes and closes this report
