### ISSUE TITLE
Creature - Northern Barrens : Affray Spectator

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#76]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[6249](https://cata-twinhead.twinstar.cz/?npc=6249)_**

The Current Behaviour is as following: 
**_This creature located at 78.9 / 90.9, is standing under water under the dock._**

Expected Behaviour should be as following: 
**_No idea where he belongs, but not there ;)_**

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Creature was removed.

//Fixes and closes this report
