### ISSUE TITLE
Quest - Northern Barrens : Wanted: Cap'n Garvey

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#77]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[895](https://cata-twinhead.twinstar.cz/?quest=895)_**

The Current Behaviour is as following: 
**_Upon accepting this quest, the [quest item](https://cata-twinhead.twinstar.cz/?item=5084) appears in your bags_**

Expected Behaviour should be as following: 
_**This quest works fine, by killing the Captain and looting his head**_

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by UtilExe** [comment]
Fixed
