### ISSUE TITLE
Quest - Northern Barrens : Mutiny, Mon!

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#78]
Quest/Spell/Item/Creature(ID) The ID is: 
[14063](https://cata-twinhead.twinstar.cz/?quest=14063)

The Current Behaviour is as following: 
**_This quest auto completes_**

Expected Behaviour should be as following: 
**_You're supposed to go on the boat and use the [quest item](https://cata-twinhead.twinstar.cz/?item=46838)_**
_**The quest item doesn't work**_

Screenshot/Video (IMGUR/YOUTUBE): 
**_https://www.youtube.com/watch?v=-JZimMOkqEM_**

Additional Information:

**Comment by UtilExe** [comment]
Finally fixed :)
