### ISSUE TITLE
Creature - Northern Barrens : Lost Barrens kodo

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#81]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[3234](https://cata-twinhead.twinstar.cz/?npc=3234)_**

The Current Behaviour is as following:
**_These are all "dead" but you can still attack and kill them_** 

Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE):
**_https://gyazo.com/e26b5d2dd59b0a00ef8bb0c87396ae7d_** 

Additional Information:

**Comment by omghixd** [comment]
These are no longer targetable and no longer kill-able.

//Fixes and closes this report
