### ISSUE TITLE
Quest - Northern Barrens : Gazlowe's Fortune

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#82]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[14050](https://cata-twinhead.twinstar.cz/?quest=14050)_**

The Current Behaviour is as following:
**_You can loot the objective and quest item just fine (coords 66.3 / 77.6)_** 

Expected Behaviour should be as following:
**_When you loot the objective, [Baron Longshore](https://cata-twinhead.twinstar.cz/?npc=3467) and 1 [Southsea Cutthroat](https://cata-twinhead.twinstar.cz/?npc=3383) should spawn and attack you_**
**_Check Baron's dialogue upon spawning_**

Screenshot/Video (IMGUR/YOUTUBE):
**_https://www.youtube.com/watch?v=0wqUShi3evY_** 

Additional Information:

**Comment by omghixd** [comment]
Re-Scripted the event, Baron and 1 Southsea Cutthroat spawns and will attack you, Baron also yells his dialogue upon spawn.

//Fixes and closes this report
