### ISSUE TITLE
Quest - Northern Barrens : Ammo kerblammo

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#83]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[14042](https://cata-twinhead.twinstar.cz/?quest=14042)_**

The Current Behaviour is as following:
**_Quest is working fine, only the ammo dumps spawn time is to long_** 

Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Respawntimer was changed from 120s to 60s instead.

//Fixes and closes this report
