### ISSUE TITLE
Quest - Return to Razor Hill

### ISSUE THREAD

**Issue by Yukki69** [omghixd/Path-of-Classic-Bugtracker#85]
Quest/Spell/Item/Creature(ID) The ID is: 6386

The Current Behaviour is as following: The tracked quest is incorrectly explained compared to the one in the quest log.

Expected Behaviour should be as following: The the tracked quest must have the same description like the one in quest log.

Screenshot/Video (IMGUR/YOUTUBE): https://i.imgur.com/unVehkS.png

Additional Information:

**Comment by omghixd** [comment]
Corrected the text shown on the right side of the screenshot.

//Fixes and closes this report
