### ISSUE TITLE
Quest -Northern Barrens : Waptor Twapping

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#86]
Quest/Spell/Item/Creature(ID) The ID is:
**_[34828](https://cata-twinhead.twinstar.cz/?npc=34828)_** 

The Current Behaviour is as following: 
**_This quest auto completes_**

Expected Behaviour should be as following: 
**_Need to check this whole quest and [quest item](https://cata-twinhead.twinstar.cz/?item=46853)_**

Screenshot/Video (IMGUR/YOUTUBE): 
**_https://www.youtube.com/watch?v=EPNYaoH9o8M_**

Additional Information:

**Comment by UtilExe** [comment]
Fixed + fixed condition
