### ISSUE TITLE
Quest - Northern Barrens: King of Centaur Mountain

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#87]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[13995](https://cata-twinhead.twinstar.cz/?quest=13995)_**

The Current Behaviour is as following: 
**_Upon accepting this quest, Gorgal Angerscar does not enact his script or dialogue_**
**_Kurak and a companion are already spawned_**
**_the "Horde Banner" on the mountain to the left is already spawned_**

Expected Behaviour should be as following: 
**_Upon accepting the quest, you should follow Gorgal Angerscar up to the mountain on your left.
He should plant the "Horde Banner" there, and it should start to spawn waves of Kolkar creatures, with as last Kurak_**

Screenshot/Video (IMGUR/YOUTUBE): 
**_https://www.youtube.com/watch?v=IO0QJBnS9OI_**

Additional Information:

**Comment by omghixd** [comment]
Confirmed. Will script this later on.

**Comment by UtilExe** [comment]
Scripted
