### ISSUE TITLE
Creature - Northern Barrens : Hezrul Bloodmark

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#88]
Quest/Spell/Item/Creature(ID) The ID is:
**_[3396](https://cata-twinhead.twinstar.cz/?npc=3396)_**

The Current Behaviour is as following: 
**_When pulling this creature, you don't aggro his bodyguards_**

Expected Behaviour should be as following: 
**_He should have a 100% drop chance on [5025](https://cata-twinhead.twinstar.cz/?item=5025)_**

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
The creatures near him (his 2 followers) will now also assist Henzrul when pulled. The item also has been given a 100% Drop Chance instead of 91%.

//Fixes and closes this report
