### ISSUE TITLE
Item - Northern Barrens : Centaur Bracer

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#89]
Quest/Spell/Item/Creature(ID) The ID is: 
**_[5030](https://cata-twinhead.twinstar.cz/?item=5030)_**

The Current Behaviour is as following: 

Expected Behaviour should be as following: 
**_This item should have the following drop rates_**

**_[32745](https://cata-twinhead.twinstar.cz/?npc=3275) 65%_**
**_[9523](https://cata-twinhead.twinstar.cz/?npc=9523) 65%_**

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Drop rates are now 65% for both creatures

//Fixes and closes this report
