### ISSUE TITLE
Quest - Northern Barrens : Counterattack!

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#90]
Quest/Spell/Item/Creature(ID) The ID is: 
_**[4021](https://cata-twinhead.twinstar.cz/?quest=4021)**_

The Current Behaviour is as following: 

Expected Behaviour should be as following: 
**_You should be able to loot the banner from the warlord you kill, not the banner that's already spawned_**

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Removed the static spawned banner. Warlord Krom'zar will also spawn a new one shortly after killed.
