### ISSUE TITLE
Creature - Northern Barrens : Burning Blade Mount

### ISSUE THREAD

**Issue by mikedej** [omghixd/Path-of-Classic-Bugtracker#91]
Quest/Spell/Item/Creature(ID) The ID is:
**_[52337](https://cata-twinhead.twinstar.cz/?npc=52337)_** 

The Current Behaviour is as following: 
**_They are hostile, but don't attack. You can kill them though_**

Expected Behaviour should be as following: 
**_Not sure if they should be spawned. Perhaps for a quest or they should be mounted?_**

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
Can you specify where in the Northern Barrens this takes place?

**Comment by mikedej** [comment]
The road leading up the Ashenvale

**Comment by omghixd** [comment]
These arent suppose to be spawned. They are a part of a cinematic like quest. A sniffer most likely snatched it when it was collecting data a long time ago. Removed the "Cinematic" NPCs and the surrounding area containing quite a lot of Dupes entitled to other quests etc.

//Fixes and closes this report
