### ISSUE TITLE
Item Quest - Gorat's Imbued Blood

### ISSUE THREAD

**Issue by YukkiKun** [omghixd/Path-of-Classic-Bugtracker#93]
Quest/Spell/Item/Creature(ID) The ID is: 45023

The Current Behaviour is as following: I am near Groat's body and when I try to return his spirit the item quest says that i require Groat's corpse.

Expected Behaviour should be as following: Returns Gorat's spirit to his body for a short time

Screenshot/Video (IMGUR/YOUTUBE): [Screenshot](https://media.discordapp.net/attachments/772161310191255612/779021513512714290/unknown.png?width=845&height=475)

Additional Information:

**Comment by UtilExe** [comment]
Fixed + scripted the entire quest
