### ISSUE TITLE
Quest - Never Trust a Big Barb and a Smile

### ISSUE THREAD

**Issue by Sundorian** [omghixd/Path-of-Classic-Bugtracker#96]
Quest/Spell/Item/Creature(ID) The ID is: 25165

The Current Behaviour is as following: Using the Poison Extraction Totem (id:52505) doesnt matter when collecting a Sample of Scorpid Venom.  You still get credit for collecting them

Expected Behaviour should be as following: You need to cast the Poison Extraction Totem during the Clattering Scorpids casting of "Envemon" only then can you collect a sample of scropid venom to complete the quest

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by UtilExe** [comment]
Fixed
