### ISSUE TITLE
Quest - Riding on

### ISSUE THREAD

**Issue by Sundorian** [omghixd/Path-of-Classic-Bugtracker#97]
Quest/Spell/Item/Creature(ID) The ID is: 25171

The Current Behaviour is as following: Click on Raider Jhash, a window opens with the phrase "Can I have a ride to Razor Hill?"  Click on that, it teleports you to Razor Hill.

Expected Behaviour should be as following: You should ride Raider Jhash's wolf to Razor Hill

Screenshot/Video (IMGUR/YOUTUBE): ![WoWScrnShot_112220_160735](https://user-images.githubusercontent.com/45952468/99918975-1b76d080-2ce0-11eb-99ce-cda399a6dbc0.jpg)

Additional Information:

**Comment by UtilExe** [comment]
Should be improved. Lmk if issues about the pathing.
