### ISSUE TITLE
Quest - Northern Stranglethorn : Control Sample

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#99]
Quest/Spell/Item/Creature(ID) The ID is: 26733

The Current Behaviour is as following: When I kill the Basilisks they despawn immediately so there is no loot.

Expected Behaviour should be as following: The basilisks should lie dead so that you can loot them like other mobs.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
I have tried both with and without having Lashtail Hatchling summoned but the behaviour is the same. Was not able to complete quest.

**Comment by UtilExe** [comment]
Fixed
